# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev39+g17967af.d20230110"
__version_tuple__ = version_tuple = (0, 1, "dev39", "g17967af.d20230110")
